version: '3.8'

services:
  mysql:
    container_name: rrm-mysql
    image: mysql
    platform: linux/amd64
    restart: always
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
